spin_manifest_version = 2

[application]
name = "bioboost-reps"
version = "0.1.0"
authors = ["Raymond <hello@raymondkneipp.com>"]
description = "deploy a leptos CSR app with Spin"

[[trigger.http]]
route = "/..."
component = "leptos-with-spin"

[component.leptos-with-spin]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "dist", destination = "/" }]
# use this fallback so that Spin works well with the Leptos router
environment = { FALLBACK_PATH = "index.html" }
